export type TripState =
  | 'REQUESTED'
  | 'ACCEPTED'
  | 'DRIVER_ARRIVED'
  | 'IN_PROGRESS'
  | 'COMPLETED'
  | 'CANCELLED'
  | 'NO_DRIVERS'
  | 'PASSENGER_CANCELLED'
  | 'DRIVER_CANCELLED';

export const TRIP_STATES: Record<TripState, TripState> = {
  REQUESTED: 'REQUESTED',
  ACCEPTED: 'ACCEPTED',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_DRIVERS: 'NO_DRIVERS',
  PASSENGER_CANCELLED: 'PASSENGER_CANCELLED',
  DRIVER_CANCELLED: 'DRIVER_CANCELLED',
};

export default TRIP_STATES;
